services:
    node-exporter:
        pid: host
        network_mode: host
        volumes:
            - '/:/host:rw,rslave'
        image: 'quay.io/prometheus/node-exporter:latest'

    prometheus:
        container_name: prometheus1
        ports:
            - '9080:9090' 
        volumes:
            - '/home/administrator/prom/Prometheus/:/etc/prometheus/' 
        image: prom/prometheus

    grafana:
        container_name: grafana1
        ports:
            - '3001:3000' 
        image: grafana/grafana
