---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    hey:  hello
spec:
  containers:
    - name: container1
      image: httpd
      ports:
        - containerPort:  80
          name: container-port
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: container-port
      nodePort: 30303
  selector:
    hey:  hello
...
